AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cloud-challenge

  Sample SAM Template for cloud-challenge

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  BucketName:
    Type: String
    Default: mystatic-resume-website

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3Bucket
                - /*
                
  VisitorCountFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Policies:
        - DynamoDBCrudPolicy:
            TableName: VisitorCount
      CodeUri: function/
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        VisitorCount:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /visitor_count
            Method: get
            
  DynamoDBTable:
   Type: AWS::DynamoDB::Table
   Properties:
     TableName: VisitorCount
     BillingMode: PAY_PER_REQUEST
     AttributeDefinitions:
       - AttributeName: "ID"
         AttributeType: "S"
     KeySchema:
       - AttributeName: "ID"
         KeyType: "HASH"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  VisitorCountApi:
    Description: "API Gateway endpoint URL for Prod stage for Visitor Count function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/visitor_count/"
  VisitorCountFunction:
    Description: "Visitor Count Lambda Function ARN"
    Value: !GetAtt VisitorCountFunction.Arn
  VisitorCountFunctionIamRole:
    Description: "Implicit IAM Role created for Visitor Count function"
    Value: !GetAtt VisitorCountFunctionRole.Arn
