name: main
on: push
env:
  PYTHON_VERSION: 3.9
  AWS_DEFAULT_REGION: 'us-east-1'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  test-infra:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install boto3
        run:
          pip3 install boto3
      - name: test get-function
        run: cd getFunction && python3 test.py -v && cd ..
      - name: Update static files with S3
        run: aws s3 cp frontend/. s3://mystatic-resume-website/ --recursive
